apiVersion: v1
kind: Service
metadata:
  name: nginx-git-np-service
spec:
  type: NodePort
  selector:
    app: nginx-git-label
  ports:
  - nodePort: 30093
    port: 92
    targetPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-git-lb-service
spec:
  type: LoadBalancer
  selector:
    app: nginx-git-label
  ports:
    - name: http
      protocol: TCP
      port: 93
      targetPort: 80
